version: '3.3'
volumes:
  data:
services:
  app:
    build: .
    command: yarn dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVICEPORT=${SERVICEPORT}
      - DB_CLIENT=${DB_CLIENT}
      - DB_SSL=${DB_SSL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_POOL_MIN=${DB_POOL_MIN}
      - DB_POOL_MAX=${DB_POOL_MAX}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
